import type { NextPage, } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import { useEffect,useState ,useRef} from 'react'

const Home: NextPage = () => {




  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
        
      </Head>

      <main className={styles.main}>
        <div>
          <div style={{width:200,marginRight:20}}><Link href='/posts'>/posts</Link></div>
          <div style={{width:200,marginRight:20}}><Link href='/posts/12'>/posts/12</Link></div>
          <div style={{width:200,marginRight:20}}><Link href='/posts/12'>/posts/12</Link></div>
          <div style={{width:200,marginRight:20}}><Link href='/blog'>/blog</Link></div>
          <div style={{width:200,marginRight:20}}><Link href='/article'>/article</Link></div>
          <div style={{width:200,marginRight:20}}><Link href='/article/111'>/article/111</Link></div>

        </div>

        <h1 className={styles.title}>
        Welcome to
          {/* <Link href="/">Next.js!</Link> */}
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

       
      </main>

      <footer className={styles.footer}>
    
          Powered by cz
          
      </footer>
    </div>
  )
}

export default Home
